### ISSUE TITLE
When 2 requests to the same endpoint are made one after another they produce the same output.

### ISSUE THREAD

**Issue by wujekbogdan** [bradbarkhouse/mysportsfeeds-api#82] opened 2018-05-24 09:42 UTC
Call the same endpoint 2 times. Let's say `mlb/2018-regular/cumulative_player_stats.json/` with 2 different sets of `teamstats` parameter values. For example first time with `HR,RBI,AVG` then the second time with `W,L,ERA,SV`

If these 2 requests are made quickly, one after another, then responses for both of them are the same. It doesn't happen always, but it's quite easy to reproduce. Just try multiple times and finally you'll reproduce it.

**Comment by bradbarkhouse** [comment] 2018-05-24 13:10
Actually, this is a duplicate of #73 , which is slated for inclusion in the v2.0 release.

It has to do with our caching mechanism, which needs to be thread-synchronized.

**Closed as completed by bradbarkhouse** 2018-05-24 13:10 UTC
