### ISSUE TITLE
Weird format in NHL stats

### ISSUE THREAD

**Issue by mdaves93** [bradbarkhouse/mysportsfeeds-api#75] opened 2018-04-17 09:12 UTC
In NHL stats the results that come back nested oddly with Games Played being directly nested under stats and the rest of the stats being nested under a second stats block. I don't know if this is intentional for some reason. I had to make separate parsers for each sport for other reasons but this one didn't make sense to me.  I included an abbreviated json return below.

```
{
  "cumulativeplayerstats": {
    "lastUpdatedOn": "2018-04-17 2:32:49 AM",
    "playerstatsentry": [
      {
        "player": {... },
        "team": {...},
        "stats": {
          "GamesPlayed": {...},
          "stats": {All Other Stats}
          }
        }
      },
...
   }
}
```
Endpoint:
https://api.mysportsfeeds.com/v1.2/pull/nhl/2018-playoff/cumulative_player_stats.json?playerstats
https://api.mysportsfeeds.com/v1.2/pull/nhl/2018-playoff/cumulative_player_stats.xml?playerstats

**Comment by bradbarkhouse** [comment] 2018-04-17 10:47
@mdavies2393 chalk it up it a poorly designed structure in the very earliest days of API v1.0. :(  This is being corrected in API v.20 redesign, which is ongoing now!

**Comment by wujekbogdan** [comment] 2018-04-24 17:19
It's a duplicate of: https://github.com/MySportsFeeds/mysportsfeeds-api/issues/59

**Comment by bradbarkhouse** [comment] 2018-07-12 23:01
Done!

**Closed as completed by bradbarkhouse** 2018-07-12 23:01 UTC
